# Generated by Django 2.2.5 on 2019-10-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('launch_region_id', models.CharField(max_length=10)),
                ('driver_id', models.CharField(max_length=10)),
                ('customer_id', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=10)),
                ('pattern_name', models.CharField(max_length=32)),
                ('resolution', models.CharField(max_length=12)),
                ('compensation', models.CharField(max_length=32)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
