# Generated by Django 2.2.5 on 2019-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudorders',
            name='compensation',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='fraudorders',
            name='customer_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='fraudorders',
            name='order_id',
            field=models.CharField(db_index=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='fraudorders',
            name='pattern_name',
            field=models.CharField(max_length=36),
        ),
    ]
