# Generated by Django 2.2.5 on 2019-10-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_inspector', '0002_auto_20191002_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudorders',
            name='pattern_name',
            field=models.CharField(max_length=200),
        ),
    ]
