# Generated by Django 2.2.5 on 2019-10-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_inspector', '0003_auto_20191002_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='google_sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=36, unique=True)),
                ('launch_region_id', models.IntegerField()),
                ('city_gspread_key', models.CharField(max_length=150)),
                ('city_bonus_plan_dict', models.IntegerField()),
                ('bonus_plan_ver', models.IntegerField()),
                ('bonus_plan_niz', models.IntegerField()),
            ],
        ),
    ]
