# Generated by Django 2.2.5 on 2019-10-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_inspector', '0004_google_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_sheet',
            name='city',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
