# Generated by Django 2.2.5 on 2019-10-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_inspector', '0006_option_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_city',
            name='city',
            field=models.CharField(db_index=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='option_city',
            name='launch_region_id',
            field=models.IntegerField(unique=True),
        ),
    ]
