# Generated by Django 2.2 on 2019-05-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Город', models.CharField(db_index=True, max_length=20)),
                ('Код_Города', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Detalizacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Код_Города', models.CharField(db_index=True, max_length=10)),
                ('Ид_водителя_короткий', models.SlugField(max_length=10)),
                ('Ид_водителя_длинный', models.SlugField(max_length=32, unique=True)),
                ('Текущий_баланс_водителя', models.CharField(db_index=True, max_length=16)),
                ('Начисления_на_баланс_водителя_исключая_пополнения', models.CharField(db_index=True, max_length=16)),
                ('Размер_всех_доплат', models.CharField(db_index=True, max_length=16)),
                ('Размер_всех_доплат_в_потенициальных_фрод', models.CharField(db_index=True, max_length=16)),
                ('Размер_бонусов_только_из_доплат_до_минималки', models.CharField(db_index=True, max_length=16)),
                ('Текущая_сумма_бонус_плана', models.CharField(db_index=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SQL_SEL',
            fields=[
                ('id_select', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_name', models.CharField(db_index=True, max_length=30, null=True)),
                ('sql_select', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trip_dan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Код_Города', models.CharField(db_index=True, max_length=10)),
                ('Подача', models.TimeField(blank=True, null=True)),
                ('Время_заказа', models.TimeField(blank=True, null=True)),
                ('Время_заказа_БО', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Дистанция', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Старт_поездки', models.DateTimeField(blank=True, null=True)),
                ('Адрес_подачи', models.SlugField()),
                ('Время_окончания_поездки', models.DateTimeField(blank=True, null=True)),
                ('Конечный_адрес', models.SlugField(blank=True, null=True)),
                ('Промо', models.SlugField(blank=True, max_length=12, null=True)),
                ('Часть_промо', models.SlugField(blank=True, max_length=12, null=True)),
                ('Доплата', models.SlugField(blank=True, max_length=12, null=True)),
                ('Статус_поездки', models.SlugField(max_length=20, null=True)),
                ('ИД_поездки', models.SlugField(max_length=36)),
                ('ИД_клиента', models.SlugField(max_length=36)),
                ('Стасус', models.SlugField(max_length=16, null=True)),
                ('Имя_клиента', models.SlugField(max_length=36, null=True)),
                ('Телефон_клиента', models.SlugField(null=True)),
                ('Почта_клиента', models.SlugField(max_length=36, null=True)),
                ('ИД_водителя', models.SlugField(max_length=36)),
                ('Имя_водителя', models.SlugField(max_length=36, null=True)),
                ('Телефон_водителя', models.SlugField(null=True)),
                ('Почта_водителя', models.SlugField(max_length=36, null=True)),
                ('Промо_водителя', models.SlugField(max_length=36, null=True)),
                ('Статус_р', models.SlugField(max_length=16, null=True)),
            ],
        ),
    ]
